import { loadImageSourceRefs, supportsReleaseLock } from "@/lib/release-locks";

// Mirrors the real langgenius/ee-release versions.lock.yaml shape: camelCase
// `releaseTrack`, snake_case `ref_type`, and a `components` list whose entries
// reference a `source` whose commit is the per-image source hash.
const LOCK_YAML = `# AUTO-GENERATED by "make freeze" — DO NOT EDIT
version: 3.9.6
releaseTrack: lts
sources:
  - id: dify
    repo: https://github.com/langgenius/dify.git
    ref: lts/1.13.x
    ref_type: branch
    commit: 18211c159ed2af9fbf7b03a025db04c1f6dcc068
  - id: dify-enterprise
    repo: https://github.com/langgenius/dify-enterprise.git
    ref: lts/0.16.x
    ref_type: branch
    commit: 57bb36dd499e28888bc9b673af3d8e33528fa2e3
  - id: dify-sandbox
    repo: https://github.com/langgenius/dify-sandbox.git
    ref: a94a4666f2ea1871d17bd3a131187b72f7e3c95f
    ref_type: commit
    commit: a94a4666f2ea1871d17bd3a131187b72f7e3c95f
components:
  - id: api
    source: dify
    image: langgenius/dify-ee-api
  - id: gateway
    source: dify-enterprise
    image: langgenius/dify-ee-gateway
  - id: sandbox
    source: dify-sandbox
    image: langgenius/dify-ee-sandbox
  - id: orphan
    source: not-a-known-source
    image: langgenius/dify-ee-orphan
`;

const mockFetch = (init: {
  ok: boolean;
  status: number;
  text?: string;
}): jest.Mock => {
  const fn = jest.fn().mockResolvedValue({
    ok: init.ok,
    status: init.status,
    text: async () => init.text ?? "",
  });
  global.fetch = fn as unknown as typeof fetch;
  return fn;
};

describe("supportsReleaseLock", () => {
  it.each([
    ["3.8.9", false],
    ["3.9.0", true],
    ["3.9.6", true],
    ["3.10.0", true],
    ["4.0.0", true],
    ["not-semver", false],
  ])("gates %s -> %s", (version, expected) => {
    expect(supportsReleaseLock(version as string)).toBe(expected);
  });
});

describe("loadImageSourceRefs", () => {
  const originalFetch = global.fetch;

  afterEach(() => {
    global.fetch = originalFetch;
    jest.restoreAllMocks();
  });

  it("returns an empty map for versions below the minimum without fetching", async () => {
    const fetchMock = mockFetch({ ok: true, status: 200, text: LOCK_YAML });
    const refs = await loadImageSourceRefs("3.8.0");
    expect(refs.size).toBe(0);
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("maps each image repository to its source ref (repo/ref/ref_type/commit)", async () => {
    mockFetch({ ok: true, status: 200, text: LOCK_YAML });

    const refs = await loadImageSourceRefs("3.9.6");

    expect(refs.get("langgenius/dify-ee-api")).toEqual({
      repo: "https://github.com/langgenius/dify.git",
      ref: "lts/1.13.x",
      ref_type: "branch",
      commit: "18211c159ed2af9fbf7b03a025db04c1f6dcc068",
    });
    expect(refs.get("langgenius/dify-ee-gateway")?.commit).toBe(
      "57bb36dd499e28888bc9b673af3d8e33528fa2e3",
    );
    expect(refs.get("langgenius/dify-ee-sandbox")?.ref_type).toBe("commit");

    // A component pointing at an unknown source resolves to nothing.
    expect(refs.has("langgenius/dify-ee-orphan")).toBe(false);
    // Third-party images that have no component never appear.
    expect(refs.has("langgenius/redis")).toBe(false);
  });

  it("returns an empty map on 404", async () => {
    mockFetch({ ok: false, status: 404 });
    const refs = await loadImageSourceRefs("3.9.6");
    expect(refs.size).toBe(0);
  });

  it("throws on non-404 error responses", async () => {
    mockFetch({ ok: false, status: 500 });
    await expect(loadImageSourceRefs("3.9.6")).rejects.toThrow("HTTP 500");
  });

  it("throws when the payload is not a YAML mapping", async () => {
    mockFetch({ ok: true, status: 200, text: "just a scalar" });
    await expect(loadImageSourceRefs("3.9.6")).rejects.toThrow(
      "Invalid release lock payload",
    );
  });

  it("tolerates a lock without components", async () => {
    mockFetch({
      ok: true,
      status: 200,
      text: "version: 3.9.0\nsources:\n  - id: dify\n    commit: abc123\n",
    });
    const refs = await loadImageSourceRefs("3.9.0");
    expect(refs.size).toBe(0);
  });
});
